name: NAGNAE-AI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pip
  - faiss-gpu=1.7.4
  - pip:
    - accelerate==0.33.0
    - aiohttp==3.9.5
    - albumentations==1.4.11
    - apscheduler==3.10.1
    - beautifulsoup4==4.12.3
    - bitsandbytes==0.43.3
    - chromadb==0.5.5
    - datasets==2.20.0
    - docker-pycreds==0.4.0
    - elastic-transport==8.15.0
    - elasticsearch==8.15.0
    - faiss-cpu==1.8.0
    - fastapi==0.112.2
    - ffmpeg-python==0.2.0
    - gitpython==3.1.43
    - google-api-python-client==2.140.0
    - gtts==2.5.3
    - httpcore==1.0.5
    - huggingface-hub==0.24.1
    - langchain==0.2.14
    - langchain-community==0.2.12
    - langchain-core==0.2.35
    - langchain-elasticsearch==0.2.2
    - langchain-openai==0.1.22
    - langchain-text-splitters==0.2.2
    - langdetect==1.0.9
    - langid==1.1.6
    - langsmith==0.1.93
    - librosa==0.10.2.post1
    - llama-index
    - llama-index-core
    - mysqlclient
    - onnx==1.16.1
    - onnxruntime==1.18.1
    - openai==1.42.0
    - opencv-python-headless==4.10.0.84
    - pandas==2.2.2
    - peft==0.12.0
    - pinecone-client==5.0.1
    - playwright==1.45.1
    - posthog==3.5.0
    - pydantic==2.8.2
    - pymilvus==2.4.4
    - pypdf==4.3.1
    - python-dotenv==1.0.1
    - python-multipart==0.0.6
    - rank-bm25==0.2.2
    - requests==2.32.3
    - schedule==1.2.2
    - scikit-learn==1.5.1
    - selenium==4.23.1
    - sentence-transformers==3.0.1
    - spacy==3.7.5
    - SQLAlchemy==2.0.31
    - tiktoken==0.7.0
    - torch==2.4.0
    - tqdm==4.66.4
    - transformers==4.44.0
    - unidic-lite==1.0.8
    - uvicorn==0.30.6
    - wandb==0.17.5
    - webdriver-manager==4.0.2